"""
Generates index.html (the landing page: a tile grid of every page), all.html (the
aggregated "All Videos" page) and one <slug>.html per section from the SECTIONS
list in channels.py. All section pages share assets/hub.css and assets/hub.js; a page
only carries its own title, accent colour and written-feed links.

Run after editing SECTIONS or data/portal_sources.csv:
    python scripts/build_pages.py

The generated HTML is committed (GitHub Pages serves it as-is) - edit this
script or the assets, never the generated pages.
"""

import json
from html import escape
from pathlib import Path

from channels import HOME, LANDING, SECTIONS, WRITTEN_BY_SECTION, YOUTUBE_BY_SECTION

ROOT = Path(__file__).parent.parent
HEADER = "<!-- GENERATED by scripts/build_pages.py - do not edit by hand -->\n"


def with_header(html):
    """Put the notice after the doctype (a comment before it is legal but fragile)."""
    return html.replace("<!DOCTYPE html>\n", "<!DOCTYPE html>\n" + HEADER, 1)

SECTION_PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{page_title}</title>
  <link rel="manifest" href="manifest.json">
  <link rel="icon" href="icons/icon-192.png">
  <meta name="theme-color" content="{color}">
  <link rel="stylesheet" href="assets/hub.css">
</head>
<body style="--accent: {color}">

<nav>
  <a class="nav-brand" href="index.html">🧠 Applied AI Hub</a>
  <span class="nav-sep">/</span>
  <select class="nav-select" id="navSelect" aria-label="Switch section">
    <option value="">{icon} {title}</option>
{nav_options}
  </select>
</nav>

<div class="tabbar">
  <button class="tab-btn" data-tab="long" data-label="🎬 Long videos">🎬 Long videos</button>
  <button class="tab-btn" data-tab="short" data-label="⚡ Shorts">⚡ Shorts</button>
  <button class="tab-btn" data-tab="channels">📺 By Channel</button>
  <button class="tab-btn" data-tab="topics">🔥 Topics</button>
{articles_tab}</div>

<div class="toolbar">
  <div class="toolbar-group" data-tabs="long short channels topics"><span class="toolbar-label">Time</span>
    <select id="timeSelect">{time_options}</select></div>
  <div class="toolbar-group" data-tabs="long short channels"><span class="toolbar-label">Sort</span>
    <select id="sortSelect"><option value="views">👁 Views</option><option value="velocity">⚡ Velocity</option><option value="trending">📊 Trending</option><option value="newest">🕐 Newest</option></select></div>
  <div class="toolbar-group" data-tabs="topics"><span class="toolbar-label">Rank by</span>
    <select id="rankSelect"><option value="rising">🔥 Rising</option><option value="mentions">📊 Most mentioned</option></select></div>
{section_filter}  <div class="toolbar-group" data-tabs="long short channels topics articles"><span class="toolbar-label">Layer</span>
    <select id="layerSelect"><option value="all">All</option><option value="Primary">Primary (official)</option><option value="Practitioner">Practitioner</option><option value="Analysis">Analysis</option></select></div>
  <div class="toolbar-group" data-tabs="long short channels topics"><span class="toolbar-label">Language</span>
    <select id="langSelect"><option value="all">All</option><option value="en">English</option><option value="hi">Hindi</option></select></div>
  <div class="toolbar-group" data-tabs="long short channels"><span class="toolbar-label">Min views</span>
    <select id="viewsSelect"><option value="0">Any</option><option value="1000">1K+</option><option value="5000">5K+</option><option value="10000">10K+</option><option value="50000">50K+</option></select></div>
  <div class="toolbar-group" data-tabs="long short channels"><span class="toolbar-label">Duration</span>
    <select id="durationSelect"></select></div>
  <input type="search" id="searchInput" data-tabs="long short channels articles" placeholder="Search title or channel…">
</div>
<p class="meta-info" id="metaInfo"></p>

<div class="panel" id="panel-long"></div>
<div class="panel" id="panel-short"></div>
<div class="panel" id="panel-channels"></div>
<div class="panel" id="panel-topics"></div>
<div class="panel" id="panel-articles"></div>

<div class="modal-overlay" id="playerModal">
  <div class="modal-wrapper">
    <button class="modal-close" id="closeBtn" aria-label="Close">✕</button>
    <div class="modal-box">
      <div class="player-wrap"><iframe id="playerFrame" src="" allowfullscreen allow="autoplay; encrypted-media; picture-in-picture"></iframe></div>
      <div class="credit-bar" id="creditBar"></div>
    </div>
  </div>
</div>

<div class="sv" id="shortsViewer" hidden role="dialog" aria-label="Shorts viewer">
  <div class="sv-stage" id="svStage" tabindex="-1">
    <iframe id="svFrame" src="about:blank" allow="autoplay; encrypted-media; picture-in-picture" title="Short video"></iframe>
    <div class="sv-gesture" id="svGesture"></div>
    <div class="sv-info"><div class="sv-title" id="svTitle"></div><div class="sv-meta" id="svMeta"></div></div>
    <div class="sv-flash" id="svFlash"></div>
    <div class="sv-hint" id="svHint" hidden>Swipe up for next · swipe down for previous</div>
  </div>
  <div class="sv-count" id="svCount"></div>
  <button class="sv-btn sv-close" id="svClose" aria-label="Close">✕</button>
  <div class="sv-side">
    <button class="sv-btn" id="svUp" aria-label="Previous short">▲</button>
    <button class="sv-btn" id="svMute" aria-label="Mute" aria-pressed="false">🔊</button>
    <a class="sv-btn" id="svYt" href="#" target="_blank" rel="noopener noreferrer" aria-label="Open on YouTube">↗</a>
    <button class="sv-btn" id="svDown" aria-label="Next short">▼</button>
  </div>
</div>

<div id="toast"></div>
<script>window.HUB_PAGE = {page_config};</script>
<script src="assets/topics.js"></script>
<script src="assets/shorts.js"></script>
<script src="assets/hub.js"></script>
</body>
</html>
"""

# Every page offers the same windows; the data keeps 90 days (FETCH_DAYS in fetch.py).
# The first key is the default (see hub.js).
TIME_OPTIONS = [("1d", "1 day"), ("3d", "3 days"), ("7d", "7 days"), ("30d", "30 days"), ("90d", "90 days")]


INDEX_PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Applied AI Hub</title>
  <link rel="manifest" href="manifest.json">
  <link rel="icon" href="icons/icon-192.png">
  <meta name="theme-color" content="#7c5cff">
  <link rel="stylesheet" href="assets/hub.css">
  <style>
    body {{ display: flex; flex-direction: column; }}
    .hero {{ flex: 1; display: flex; flex-direction: column; align-items: center; padding: 56px 24px; text-align: center; }}
    .hero h1 {{ font-size: 2rem; color: #fff; margin-bottom: 8px; }}
    .hero p {{ color: var(--muted); margin-bottom: 44px; }}
    .grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 24px; max-width: 1000px; width: 100%; }}
    .tile {{ position: relative; background: var(--panel); border: 1px solid var(--line); border-top: 3px solid var(--accent); border-radius: 14px; padding: 36px 28px; text-decoration: none; color: inherit; text-align: center; transition: transform 0.2s, border-color 0.2s, box-shadow 0.2s; }}
    .tile:hover {{ transform: translateY(-5px); border-color: var(--accent); box-shadow: 0 8px 32px rgba(124,92,255,0.15); }}
    .tile-icon {{ font-size: 2.4rem; display: block; margin-bottom: 16px; }}
    .tile-title {{ font-size: 1.1rem; font-weight: 700; color: #fff; margin-bottom: 6px; }}
    .tile-desc {{ font-size: 0.85rem; color: var(--muted); line-height: 1.5; margin-bottom: 14px; }}
    .tile-count {{ font-size: 0.72rem; color: #666; }}
    .tile-badge {{ position: absolute; top: 14px; right: 14px; font-size: 0.7rem; font-weight: 700; padding: 3px 10px; border-radius: 20px; letter-spacing: 0.05em; text-transform: uppercase; background: var(--accent); color: #fff; }}
    .tile-badge:empty {{ display: none; }}
    @media (max-width: 480px) {{ .hero {{ padding: 36px 16px; }} .hero h1 {{ font-size: 1.5rem; }} .hero p {{ margin-bottom: 32px; }} .grid {{ gap: 16px; }} .tile {{ padding: 24px 18px; }} }}
  </style>
</head>
<body>

<nav><a class="nav-brand" href="index.html">🧠 Applied AI Hub</a></nav>

<div class="hero">
  <h1>Choose a Section</h1>
  <p>Top applied-AI videos and posts from {n_sources} hand-picked sources, ranked by popularity</p>
  <div class="grid">
{tiles}
  </div>
</div>

<script>
  // Fill each tile's badge with the number of new videos in the last 7 days.
  fetch('data/videos.json').then(r => r.json()).then(data => {{
    const since = Date.now() / 1000 - 7 * 86400;
    const count = slug => (data[slug] || []).filter(v => v.timestamp >= since && v.live_broadcast !== 'live').length;
    const slugs = {section_slugs};
    document.querySelectorAll('[data-badge]').forEach(el => {{
      const n = el.dataset.badge === 'all' ? slugs.reduce((t, s) => t + count(s), 0) : count(el.dataset.badge);
      el.textContent = n ? n + ' new' : '';
    }});
  }}).catch(() => {{}});
  if ('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js');
</script>
</body>
</html>
"""


def build_index():
    tiles = []
    for page in [HOME] + SECTIONS:
        slug = page["slug"]
        if page is HOME:
            counts = f"{sum(len(v) for v in YOUTUBE_BY_SECTION.values())} channels · all sections"
        else:
            n_wr = len(WRITTEN_BY_SECTION[slug])
            counts = f"{len(YOUTUBE_BY_SECTION[slug])} channels" + (f" · {n_wr} source{'s' if n_wr != 1 else ''}" if n_wr else "")
        tiles.append(
            f'    <a class="tile" href="{slug}.html" style="--accent: {page["color"]}">\n'
            f'      <span class="tile-badge" data-badge="{slug}"></span>\n'
            f'      <span class="tile-icon">{page["icon"]}</span>\n'
            f'      <div class="tile-title">{escape(page["title"])}</div>\n'
            f'      <div class="tile-desc">{escape(page["blurb"])}</div>\n'
            f'      <div class="tile-count">{counts}</div>\n'
            f'    </a>')
    n_sources = (sum(len(v) for v in YOUTUBE_BY_SECTION.values()) +
                 sum(len(v) for v in WRITTEN_BY_SECTION.values()))
    html = INDEX_PAGE.format(tiles="\n".join(tiles), n_sources=n_sources,
                             section_slugs=json.dumps([s["slug"] for s in SECTIONS]))
    (ROOT / "index.html").write_text(with_header(html), encoding="utf-8")


def watch_links(slugs):
    """Sources with no RSS/Atom feed: shown as direct links on the Articles tab."""
    return [{"name": w["name"], "site": w["site"]}
            for slug in slugs for w in WRITTEN_BY_SECTION[slug] if not w["feed"]]


def js_config(page, is_home):
    """The page's HUB_PAGE object, safe to inline in a <script> tag."""
    slugs = [s["slug"] for s in SECTIONS] if is_home else [page["slug"]]
    cfg = {
        "slug": page["slug"],
        "title": page["title"],
        "hasArticles": any(WRITTEN_BY_SECTION[s] for s in slugs),
        "watch": watch_links(slugs),
    }
    if is_home:
        # Home merges every section's data; the page needs these to label and filter it.
        cfg["sections"] = [{"slug": s["slug"], "title": s["title"], "icon": s["icon"]} for s in SECTIONS]
    return json.dumps(cfg, ensure_ascii=False).replace("</", "<\\/")


def build_page(page, is_home=False):
    others = [LANDING] + ([HOME] if not is_home else []) + [s for s in SECTIONS if s["slug"] != page["slug"]]
    nav_options = "\n".join(
        f'    <option value="{o["slug"]}.html">{o["icon"]} {escape(o["title"])}</option>' for o in others)
    has_articles = any(WRITTEN_BY_SECTION[s["slug"]] for s in (SECTIONS if is_home else [page]))
    articles_tab = '  <button class="tab-btn" data-tab="articles">📝 Articles</button>\n' if has_articles else ""
    section_filter = ""
    if is_home:
        opts = "".join(f'<option value="{s["slug"]}">{s["icon"]} {escape(s["title"])}</option>' for s in SECTIONS)
        section_filter = ('  <div class="toolbar-group" data-tabs="long short channels topics articles"><span class="toolbar-label">Section</span>\n'
                          f'    <select id="sectionSelect"><option value="all">All sections</option>{opts}</select></div>\n')
    time_options = "".join(f'<option value="{v}">{label}</option>' for v, label in TIME_OPTIONS)
    html = SECTION_PAGE.format(
        time_options=time_options,
        title=escape(page["title"]),
        page_title=f'{escape(page["title"])} · Applied AI Hub',
        color=page["color"], icon=page["icon"],
        nav_options=nav_options, articles_tab=articles_tab, section_filter=section_filter,
        page_config=js_config(page, is_home))
    out = f"{page['slug']}.html"   # all.html for the aggregated page
    (ROOT / out).write_text(with_header(html), encoding="utf-8")


def remove_stale_pages(expected):
    """Delete generated pages of sections that no longer exist (only files carrying our notice)."""
    for path in ROOT.glob("*.html"):
        if path.name in expected:
            continue
        if HEADER.strip() in path.read_text(encoding="utf-8")[:300]:
            path.unlink()
            print(f"Removed stale page {path.name}")


if __name__ == "__main__":
    build_index()
    build_page(HOME, is_home=True)
    for section in SECTIONS:
        build_page(section)
    remove_stale_pages({"index.html", "all.html"} | {f"{s['slug']}.html" for s in SECTIONS})
    print(f"Built index.html (landing) + all.html + {len(SECTIONS)} section pages")
